/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/emails` | `/emails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wellness` | `/wellness`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/emails` | `/emails`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/wellness` | `/wellness`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/emails${`?${string}` | `#${string}` | ''}` | `/emails${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/jobs${`?${string}` | `#${string}` | ''}` | `/jobs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tickets${`?${string}` | `#${string}` | ''}` | `/tickets${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/wellness${`?${string}` | `#${string}` | ''}` | `/wellness${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/emails` | `/emails`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/jobs` | `/jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tickets` | `/tickets`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/wellness` | `/wellness`; params?: Router.UnknownInputParams; };
    }
  }
}
